name: CI

on:
  push:
    branches: ['**']

jobs:
  build:
    uses: nix-fit-org/nix-github-workflows/.github/workflows/build-docker-image.yml@main
    with:
      image_sub_path: base/redhat
    secrets: inherit
